---

project:
    key: TESTPLAN
    plan:
        key: YAMLTEST2
        name: Testplan

stages:
    - jobs:
        - scripts:
            - echo 'Starting job 1 stage 1'
        - scripts:
            - '#!/bin/bash'
            - echo 'Starting job 2 stage 1'
            - mkdir artifacts
            - echo 'bar' > artifacts/foo
            - echo '42' > artifacts/the_answer
          interpreter: shell
          artifacts:
              - name: important artifacts
                path: artifacts/*

    - jobs:
        - scripts:
            - echo 'Starting job 1 stage 2'


